apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: node-backend
        image: 179657021511.dkr.ecr.ap-southeast-2.amazonaws.com/backend:v3
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001